version: '3.8'

services:
  web:
    build: .
    container_name: codeigniter_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - codeigniter-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: always
    environment:
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - codeigniter-network

networks:
  codeigniter-network:
    driver: bridge

volumes:
  db_data:
