version: '3.8'

services:
  app:
    build: .
    ports:
      - "8010:80"
    volumes:
      - ./codeigniter:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: ci_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
